version: "3.9"
   
services:
  db:
    image: mysql:latest
    container_name: mysql_sv
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
  web:
    image : pybo_mysql
    container_name: pybo_mysql
    restart: always
    links:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db